### ISSUE TITLE
Service not spawned

### ISSUE THREAD

**Issue by jbrepogmailcom** [fnzv/trsh#2]
Hello, after sudo supervisorctl start trsh
 I get trsh: ERROR (spawn error)

I use python3 and I had to modify install script, because it failed on python3. Any idea?

**Comment by fnzv** [comment]
Hi @jbrepogmailcom 
This repo is a bit outdated/unmantained now, did you follow the installer one liner script?
As an alternative there is an updated version in Go [here](https://github.com/fnzv/trsh-go) that may still work fine

**Comment by jbrepogmailcom** [comment]
Thanks I rewrote the python script and it is working fine.
