### ISSUE TITLE
.

### ISSUE THREAD

**Issue by scriptvpskita** [fnzv/trsh#3]

**Comment by fnzv** [comment]
Hi @scriptvpskita
This error seems strange / unrelated did you try to use the updated version of the bot here:
- https://github.com/fnzv/trsh-go ?

I think the only difference between a single chat and a group should be the chat_ids and giving the bot permissions to send messages into the group

**Comment by scriptvpskita** [comment]
wow i think i will not get reply 🥲

**Comment by scriptvpskita** [comment]
sir, did you know how fo filters args ?
i want to make args only allow alphanumeric in python based on your code

fyi
i Successfully run your code bot with using telepota :)

**Comment by fnzv** [comment]
Hi @scriptvpskita 
Your best friend is Google/Stackoverflow or Docs if you have time to read pages:
- https://stackoverflow.com/questions/354038/how-do-i-check-if-a-string-is-a-number-float

Use a function to check if the string is a digit after the input args and validate that via a condition (like an if case)

**Comment by scriptvpskita** [comment]
thank you sir :)
